#%RAML 1.0 NamedExample

{
  active: true,
  assignment_group: "Consumer Service Support",
  business_service: "All",
  category: "Hardware",
  contact_type: "Phone",
  description: "Design issue with mechanical rotor",
  escalation: 1,
  expected_start": "2020-11-03T10:42:45.943Z",
  made_sla: true,
  opened_at: "2020-11-03T10:42:45.943Z",
  priority: "5-Planning",
  short_description: "Design issue with mechanical rotor",
  state: "In Progress",
  urgency: "3-Low"
}