#%RAML 1.0 NamedExample

[
	{
		name: "Sonya",
		customerNumber: "",
		account: "A0001",
		billingCity: "",
		billingCountry: "",
		aaccountGroup: "",
		distributionChannel: "10",
		division: "00",
		languageCode: "",
		languageKey: "",
		materialNumber: "",
		message: "",
		postalCode: "",
		salesOrganization: "3000",
		address: "",
		telephone: ""
  },
	{
		name: "Customer 1",
		customerNumber: "",
		account: "A0001",
		billingCity: "",
		billingCountry: "",
		aaccountGroup: "",
		distributionChannel: "10",
		division: "00",
		languageCode: "",
		languageKey: "",
		materialNumber: "",
		message: "",
		postalCode: "",
		salesOrganization: "3000",
		address: "",
		telephone: ""
  }
]