#%RAML 1.0 DataType

description: Opportunity Data from Salesforce
type: object
properties:
  name:
    displayName: Full Name
    description: Full Name of Customer
    required: true
    type: string
  customerNumber:
    displayName: Customer Number
    description: Customer Number
    required: false
    type: string
  account:
    displayName: Account Name
    description: Account Name assigned to Customer
    required: false
    type: string
  billingCity:
    displayName: Billing City
    description: Billing City of Customer
    required: false
    type: string
  billingCountry:
    displayName: Billing Country
    description: Billing Country of Customer
    required: false
    type: string
  accountGroup:
    displayName: Account Group
    description: Account Group assigned to Customer
    required: false
    type: string
  distributionChannel:
    displayName: Distribution Channel
    description: Distribution Channel
    required: false
    type: string
  division:
    displayName: Division
    description: Division
    required: false
    type: string
  languageCode:
    displayName: Language Code
    description: Language Code
    required: false
    type: string
  languageKey:
    displayName: Language Key
    description: Language Key
    required: false
    type: string
  materialNumber:
    displayName: Material Number
    description: Material Number
    required: false
    type: string
  message:
    displayName: Message
    description: Message
    required: false
    type: string
  postalCode:
    displayName: Postal Code
    description: Postal Code
    required: false
    type: string
  salesOrganization:
    displayName: Sales Organization
    description: Sales Organization
    required: false
    type: string
  address:
    displayName: Address
    description: Address
    required: false
    type: string
  telephone:
    displayName: Telephone
    description: Telephone
    required: false
    type: string